### ISSUE TITLE
Discovery List

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_QT#1]
Currently  KeePassXC connects to first PASSWORDVLT it finds.  We need to display a list to the user, so we can pick the card we want to connect.

**Comment by nidhi18apr** [comment]
KeepassXC connects to paired device. In Windows. there is no win32 API for searching the BLE Device.

https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/3b62bdbf-9a55-4c0f-becf-f4e91d4bc027/windows-8-bluetooth-le-and?forum=wdk&forum=wdk

**Comment by bravozulu1** [comment]
The pairing will be manual process.  The setup wizard Sid is working on will take them to the Windows Bluetooth settings.
