### ISSUE TITLE
BLE Discovery

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_QT#11]
You must search by UUID and not the name PASSWORDVLT.   Can you use the UUID, instead of the name?

**Comment by nidhi18apr** [comment]
Which UUID ? Device or service ?
After finding device named "PASSWORDVLT" , it looks for service and characteristics with the specified UUIDs.

**Comment by bravozulu1** [comment]
Do not search by device name.  Search by service UUID.
