### ISSUE TITLE
Approve All Entry Requests By Browser

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_QT#14]
Can we allow all requests from the browser plug-in?  Currently we have to click a dialog for every entry to give it access.

**Comment by nidhi18apr** [comment]
Can u please attach screenshot of the dialog mentioned above.

**Comment by nidhi18apr** [comment]
Can u please attach screenshot of the dialog mentioned above.

**Comment by bravozulu1** [comment]
This is just a default setting that needs to be turned on or enabled.

**Comment by bravozulu1** [comment]
Cancel ticket.  Create a new one to contain all settings.
