### ISSUE TITLE
Mac Application Icon

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_QT#15]
We need the application icon updated.

![boards_ _blustor_passwordvault_qt_and_inbox_-_bravozulumail_gmail_com_-_gmail](https://user-images.githubusercontent.com/10087224/29433051-5c4db49a-8363-11e7-9f05-0fd7a074fc4b.jpg)

**Comment by nidhi18apr** [comment]
icon files is copied during packaging. Check DMG File. It has application icon.

**Comment by bravozulu1** [comment]
Ok, we can test when we create the DWG package.
