### ISSUE TITLE
Missing pairingwizarddialog.ui in 20170822_sid_m_issues branch

### ISSUE THREAD

**Issue by madiver** [BluStor/PasswordVault_QT#16]
Looks like pairingwizarddialog.ui was not checked into the 20170822_sid_m_issues branch so I can not test the build issues.

**Comment by bravozulu1** [comment]
I've reached out to Sid on Skype, regarding this ticket.

**Comment by zefreelance2012** [comment]
Just pushed the necessary files. Please check.

**Comment by zefreelance2012** [comment]
@madiver: Thanks a lot :pray: for fixing the issue! I can now work on further steps.

So, am I allowed to close this issue? Or one of you will take care of that.
Please suggest before closing the issue - or even better :relaxed: tell me to close it.

**Comment by madiver** [comment]
Please add set(CMAKE_AUTORCC ON) to your main CMakelist.txt file and your images should appear.
