### ISSUE TITLE
Default Entry Save Location

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_QT#25]
I don't know if this is possible.

Can we save the default save location of entries?  They appear to always save in side the group called "KeePassHttp Passwords".  Which is not easy for an average person to realize where the entries are being saved and move to groups.

**Comment by madiver** [comment]
New default root folder is now called "Passwords" instead of "Root". KeePassHttp is now coded to use that as it's default group when adding new entries.  You need to make sure your root folder is called "Passwords" for this to work as intended or it will simply create a sub-folder.

**Comment by bravozulu1** [comment]
Looks good
