### ISSUE TITLE
Progress Bar Save Operations

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_QT#5]
Each save operation should show the user a progress bar indicating a save.

**Comment by nidhi18apr** [comment]
Attached is the screenshot of Database Window. Please specify where to put progress bar ?
![keepassxdbwindow](https://user-images.githubusercontent.com/25238626/28764061-81b2ae6a-7577-11e7-99d7-b3a4fce52186.png)

**Comment by bravozulu1** [comment]
Can you have a pop-up dialog box and progress bar?   The user should not be able to make more changes until the save is complete.

**Comment by bravozulu1** [comment]
@nidhi18apr  I think the progress bar work is complete?
