### ISSUE TITLE
Automatic Setup of Browsers

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_QT#8]
Currently KeePass prompts the user for a name of the browser trying to connect for the first time.  The user must pick a unique name for each browser to it will create problems.  We would like to hide this setup from the user.

Can we add a parameter that will pass the name of the window and add a random number appended to the name to create the name/key value that is stored in the "KeePassHttp Settings".

![keepasshttp setting](https://user-images.githubusercontent.com/10087224/29128471-8fc62d00-7ce9-11e7-920f-7cc0ce336236.PNG)

![keepasshttp setting keys](https://user-images.githubusercontent.com/10087224/29128475-9384e7e2-7ce9-11e7-8da2-f17ccf592b0b.PNG)

**Comment by nidhi18apr** [comment]
In https communication between browser extension and Keepassxc app , there is no parameter related to browser information. So its not possible to get the window name. Please check the parameters sent from chromeIpass for "associate" request in the attached screenshot.

**Comment by nidhi18apr** [comment]
![browserrequest](https://user-images.githubusercontent.com/25238626/29391175-2edf0824-82aa-11e7-8348-3e5b6247d72f.png)

**Comment by bravozulu1** [comment]
Where did you see these fields?   Can we use some of these empty fields?

**Comment by nidhi18apr** [comment]
I found these fields during debugging in file "src/http/Server.cpp"
"void Server::associate(const Request& r, Response * protocolResp)"
These are the values from the browser extension. The "Id" (name specified by user) is returned back to browser extension. 
Shall I try for a random string ?
